### ISSUE TITLE
XmlReader always runs TextCoverageReportFormatter and dumps it to stdout

### ISSUE THREAD

**Issue by eyck** [fvutils/pyucis#13]
Whenever an XML file is read a coverage report is generated. Is this on purpose? Or can this be removed?
Esp. in regression setups this is unfortuante as it clobbers the output when running own scripts.

**Comment by mballance** [comment]
Ah, looks like an oversight. This can definitely be removed.

**Comment by mballance** [comment]
This is resolved in the latest release (0.0.8)
